name: stormreports

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-stormreports:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Build storm reports JSON
        run: |
          python scripts/build_stormreports.py

      - name: Commit updated JSON
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add data/stormreports.json

          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "Update storm reports"
          git push
